[송선권] 숫자야구게임 구현
BCSDLab/java-baseball-playground pull request #6
Opened 2023-03-18 18:10 UTC by songsunkook

늦게 제출해서 죄송합니다.
클린 코딩을 신경써가면서 하고 싶었지만 막상 해보니 모든 면에서 엉망진창인 것 같습니다..
많이 부족할 것이라고 생각하고, 피드백해주시는 부분에 대해서는 감사하게 수용하겠습니다..!!

2023-03-19 02:50 UTC, Invidam commented on src/main/java/main.java
> +        if(result.equals("3스트라이크"))
로직에 중요 부분이니 static, enum 관리되면 좋을 것 같아요~

2023-03-19 02:50 UTC, Invidam commented on src/test/java/NumberBaseballTest.java
> +    @DisplayName("input")
입력에 관한 테스트도 필요할까요?

2023-03-19 02:50 UTC, Invidam commented on src/main/java/NumberBaseball.java
> +    int inputNumbers[], computerNumbers[];
int[] -> List<Integer> -> 별도 객체로 분리
가 되면 이상적일 것 같아요!

+) 래퍼 클래스를 자주 사용하면 관리가 더 편할 것 같아요

2023-03-19 05:57 UTC, Choi-JJunho requested changes
전체적으로 절차지향적으로 코드가 작성된 것 같아요~
아직 자바를 학습할 기회가 없어서인지 자바 API를 사용하는 모습이 낯설어보이네요

다른 사람들의 코드를 참고하면서 List, Set, String 등 과 관련된 다양한 Java API를 사용해보는 것을 추천드려요~

2023-03-19 05:57 UTC, Choi-JJunho commented on src/main/java/NumberBaseball.java
> +    int strike, ball;
접근제어자가 없네요~

> 접근제어자 : private, protected, public 과 같이 접근 범위를 지정해주는 제어자.

접근제어자가 없으면 어떤 일이 발생할까요?

2023-03-19 05:57 UTC, Choi-JJunho commented on src/main/java/main.java
> +
개행을 두개 둔 이유가 있을까요~?

2023-03-19 08:51 UTC, songsunkook commented on src/main/java/NumberBaseball.java
> +    int strike, ball;
객체와 전혀 관련이 없는 다른 객체에서도 해당 객체의 메서드는 물론 내부 변수들까지 직접적으로 접근이 가능해져서 코드가 난잡해질 수 있을 것 같습니다.
이후부터는 접근제어자를 반드시 명시하는 방향으로 코딩하도록 하겠습니다!

2023-03-19 12:59 UTC, songsunkook commented on src/main/java/main.java
> +
개행에 크게 신경쓰고 코딩을 하지 않아서 발생한 것 같습니다.
좀 더 유의해서 작성하겠습니다!

2023-03-21 00:50 UTC, Kim-Juwon commented on src/main/java/NumberBaseball.java
> +    int inputBigNum;
`~~~Num` 보다는 `~~~Number`와 같이 풀네임을 적어주는 것이 좋을 것 같습니다.

2023-03-21 00:50 UTC, Kim-Juwon commented on src/main/java/main.java
> +        System.out.println("게임을 새로 시작하려면 1, 종료하려면 2를 입력하세요.");
문자열을 직접 입력하기 보단
private static final로 상수를 정의해서 사용해보세요!

2023-03-23 01:37 UTC, closed without merging